# Generated by Django 5.0.6 on 2024-07-04 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("clg_name", models.CharField(max_length=255)),
                ("clg_code", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uty_name", models.CharField(max_length=255)),
                ("uty_code", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dept_name", models.CharField(max_length=255)),
                ("dept_code", models.CharField(max_length=255)),
                (
                    "clg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.college"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("course_name", models.CharField(max_length=255)),
                ("course_code", models.CharField(max_length=255)),
                ("year", models.BigIntegerField(blank=True, null=True)),
                ("grad_level", models.CharField(max_length=1)),
                (
                    "dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("uty_regno", models.CharField(max_length=25)),
                ("year", models.BigIntegerField(blank=True, null=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.college"
                    ),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.department"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="college",
            name="uty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.university"
            ),
        ),
    ]
